version: "3"

networks:
  mern-app:
    driver: bridge
    
services:
  front-end:
    build: ./react-front-end
    volumes:
      - ./react-front-end:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - mern-app
    environment:
      - CHOKIDAR_USEPOLLING=true
  
  api:
    build: ./express-api
    volumes:
      - ./express-api:/usr/src/app
    ports:
      - 5000:5000
    networks:
      - mern-app
    environment:
      - CHOKIDAR_USEPOLLING=true
  
  mongo:
    image: mongo
    ports: 
      - '27017:27017'
    networks:
      - mern-app


